### ISSUE TITLE
Apache Superset requires SQLAlchemy 1.4.x

### ISSUE THREAD

**Issue by jwoehr** [IBM/sqlalchemy-ibmi#147] opened 2023-10-11 16:57 UTC
With the demise of IBM i Db2 Web Query, access to open source solution Apache Superset becomes critical.
Can we get an update of sqlalchemy-ibmi that support SQLAlchemy >=1.4.49 so we can use Apache Superset please?

**Comment by kadler** [comment] 2023-11-21 16:48
This is a duplicate of #133

**Closed by kadler** 2023-11-21 16:48 UTC
